<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->delete();

		$countries = array(
			array(
                'id' => 1,
                'code' => 'US',
                'name' => 'United States',
                'alias' => Str::slug('United States'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 2,
                'code' => 'CA',
                'name' => 'Canada',
                'alias' => Str::slug('Canada'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 3,
                'code' => 'AF',
                'name' => 'Afghanistan',
                'alias' => Str::slug('Afghanistan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 4,
                'code' => 'AL',
                'name' => 'Albania',
                'alias' => Str::slug('Albania'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 5,
                'code' => 'DZ',
                'name' => 'Algeria',
                'alias' => Str::slug('Algeria'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 6,
                'code' => 'AS',
                'name' => 'American Samoa',
                'alias' => Str::slug('American Samoa'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 7,
                'code' => 'AD',
                'name' => 'Andorra',
                'alias' => Str::slug('Andorra'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 8,
                'code' => 'AO',
                'name' => 'Angola',
                'alias' => Str::slug('Angola'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 9,
                'code' => 'AI',
                'name' => 'Anguilla',
                'alias' => Str::slug('Anguilla'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 10,
                'code' => 'AQ',
                'name' => 'Antarctica',
                'alias' => Str::slug('Antarctica'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 11,
                'code' => 'AG',
                'name' => 'Antigua and/or Barbuda',
                'alias' => Str::slug('Antigua and/or Barbuda'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 12,
                'code' => 'AR',
                'name' => 'Argentina',
                'alias' => Str::slug('Argentina'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 13,
                'code' => 'AM',
                'name' => 'Armenia',
                'alias' => Str::slug('Armenia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 14,
                'code' => 'AW',
                'name' => 'Aruba',
                'alias' => Str::slug('Aruba'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 15,
                'code' => 'AU',
                'name' => 'Australia',
                'alias' => Str::slug('Australia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 16,
                'code' => 'AT',
                'name' => 'Austria',
                'alias' => Str::slug('Austria'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 17,
                'code' => 'AZ',
                'name' => 'Azerbaijan',
                'alias' => Str::slug('Azerbaijan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 18,
                'code' => 'BS',
                'name' => 'Bahamas',
                'alias' => Str::slug('Bahamas'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 19,
                'code' => 'BH',
                'name' => 'Bahrain',
                'alias' => Str::slug('Bahrain'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 20,
                'code' => 'BD',
                'name' => 'Bangladesh',
                'alias' => Str::slug('Bangladesh'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 21,
                'code' => 'BB',
                'name' => 'Barbados',
                'alias' => Str::slug('Barbados'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 22,
                'code' => 'BY',
                'name' => 'Belarus',
                'alias' => Str::slug('Belarus'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 23,
                'code' => 'BE',
                'name' => 'Belgium',
                'alias' => Str::slug('Belgium'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 24,
                'code' => 'BZ',
                'name' => 'Belize',
                'alias' => Str::slug('Belize'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 25,
                'code' => 'BJ',
                'name' => 'Benin',
                'alias' => Str::slug('Benin'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 26,
                'code' => 'BM',
                'name' => 'Bermuda',
                'alias' => Str::slug('Bermuda'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 27,
                'code' => 'BT',
                'name' => 'Bhutan',
                'alias' => Str::slug('Bhutan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 28,
                'code' => 'BO',
                'name' => 'Bolivia',
                'alias' => Str::slug('Bolivia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 29,
                'code' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'alias' => Str::slug('Bosnia and Herzegovina'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 30,
                'code' => 'BW',
                'name' => 'Botswana',
                'alias' => Str::slug('Botswana'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 31,
                'code' => 'BV',
                'name' => 'Bouvet Island',
                'alias' => Str::slug('Bouvet Island'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 32,
                'code' => 'BR',
                'name' => 'Brasil',
                'alias' => Str::slug('Brasil'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 33,
                'code' => 'IO',
                'name' => 'British lndian Ocean Territory',
                'alias' => Str::slug('British lndian Ocean Territory'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 34,
                'code' => 'BN',
                'name' => 'Brunei Darussalam',
                'alias' => Str::slug('Brunei Darussalam'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 35,
                'code' => 'BG',
                'name' => 'Bulgaria',
                'alias' => Str::slug('Bulgaria'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 36,
                'code' => 'BF',
                'name' => 'Burkina Faso',
                'alias' => Str::slug('Burkina Faso'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 37,
                'code' => 'BI',
                'name' => 'Burundi',
                'alias' => Str::slug('Burundi'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 38,
                'code' => 'KH',
                'name' => 'Cambodia',
                'alias' => Str::slug('Cambodia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 39,
                'code' => 'CM',
                'name' => 'Cameroon',
                'alias' => Str::slug('Cameroon'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 40,
                'code' => 'CV',
                'name' => 'Cape Verde',
                'alias' => Str::slug('Cape Verde'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 41,
                'code' => 'KY',
                'name' => 'Cayman Islands',
                'alias' => Str::slug('Cayman Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 42,
                'code' => 'CF',
                'name' => 'Central African Republic',
                'alias' => Str::slug('Central African Republic'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 43,
                'code' => 'TD',
                'name' => 'Chad',
                'alias' => Str::slug('Chad'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 44,
                'code' => 'CL',
                'name' => 'Chile',
                'alias' => Str::slug('Chile'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 45,
                'code' => 'CN',
                'name' => 'China',
                'alias' => Str::slug('China'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 46,
                'code' => 'CX',
                'name' => 'Christmas Island',
                'alias' => Str::slug('Christmas Island'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 47,
                'code' => 'CC',
                'name' => 'Cocos (Keeling) Islands',
                'alias' => Str::slug('Cocos (Keeling) Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 48,
                'code' => 'CO',
                'name' => 'Colombia',
                'alias' => Str::slug('Colombia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 49,
                'code' => 'KM',
                'name' => 'Comoros',
                'alias' => Str::slug('Comoros'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 50,
                'code' => 'CG',
                'name' => 'Congo',
                'alias' => Str::slug('Congo'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 51,
                'code' => 'CK',
                'name' => 'Cook Islands',
                'alias' => Str::slug('Cook Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 52,
                'code' => 'CR',
                'name' => 'Costa Rica',
                'alias' => Str::slug('Costa Rica'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 53,
                'code' => 'HR',
                'name' => 'Croatia (Hrvatska)',
                'alias' => Str::slug('Croatia (Hrvatska)'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 54,
                'code' => 'CU',
                'name' => 'Cuba',
                'alias' => Str::slug('Cuba'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 55,
                'code' => 'CY',
                'name' => 'Cyprus',
                'alias' => Str::slug('Cyprus'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 56,
                'code' => 'CZ',
                'name' => 'Czech Republic',
                'alias' => Str::slug('Czech Republic'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 57,
                'code' => 'CD',
                'name' => 'Democratic Republic of Congo',
                'alias' => Str::slug('Democratic Republic of Congo'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 58,
                'code' => 'DK',
                'name' => 'Denmark',
                'alias' => Str::slug('Denmark'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 59,
                'code' => 'DJ',
                'name' => 'Djibouti',
                'alias' => Str::slug('Djibouti'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 60,
                'code' => 'DM',
                'name' => 'Dominica',
                'alias' => Str::slug('Dominica'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 61,
                'code' => 'DO',
                'name' => 'Dominican Republic',
                'alias' => Str::slug('Dominican Republic'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 62,
                'code' => 'TP',
                'name' => 'East Timor',
                'alias' => Str::slug('East Timor'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 63,
                'code' => 'EC',
                'name' => 'Ecudaor',
                'alias' => Str::slug('Ecudaor'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 64,
                'code' => 'EG',
                'name' => 'Egypt',
                'alias' => Str::slug('Egypt'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 65,
                'code' => 'SV',
                'name' => 'El Salvador',
                'alias' => Str::slug('El Salvador'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 66,
                'code' => 'GQ',
                'name' => 'Equatorial Guinea',
                'alias' => Str::slug('Equatorial Guinea'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 67,
                'code' => 'ER',
                'name' => 'Eritrea',
                'alias' => Str::slug('Eritrea'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 68,
                'code' => 'EE',
                'name' => 'Estonia',
                'alias' => Str::slug('Estonia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 69,
                'code' => 'ET',
                'name' => 'Ethiopia',
                'alias' => Str::slug('Ethiopia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 70,
                'code' => 'FK',
                'name' => 'Falkland Islands (Malvinas)',
                'alias' => Str::slug('Falkland Islands (Malvinas)'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 71,
                'code' => 'FO',
                'name' => 'Faroe Islands',
                'alias' => Str::slug('Faroe Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 72,
                'code' => 'FJ',
                'name' => 'Fiji',
                'alias' => Str::slug('Fiji'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 73,
                'code' => 'FI',
                'name' => 'Finland',
                'alias' => Str::slug('Finland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 74,
                'code' => 'FR',
                'name' => 'France',
                'alias' => Str::slug('France'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 75,
                'code' => 'FX',
                'name' => 'France, Metropolitan',
                'alias' => Str::slug('France, Metropolitan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 76,
                'code' => 'GF',
                'name' => 'French Guiana',
                'alias' => Str::slug('French Guiana'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 77,
                'code' => 'PF',
                'name' => 'French Polynesia',
                'alias' => Str::slug('French Polynesia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 78,
                'code' => 'TF',
                'name' => 'French Southern Territories',
                'alias' => Str::slug('French Southern Territories'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 79,
                'code' => 'GA',
                'name' => 'Gabon',
                'alias' => Str::slug('Gabon'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 80,
                'code' => 'GM',
                'name' => 'Gambia',
                'alias' => Str::slug('Gambia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 81,
                'code' => 'GE',
                'name' => 'Georgia',
                'alias' => Str::slug('Georgia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 82,
                'code' => 'DE',
                'name' => 'Germany',
                'alias' => Str::slug('Germany'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 83,
                'code' => 'GH',
                'name' => 'Ghana',
                'alias' => Str::slug('Ghana'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 84,
                'code' => 'GI',
                'name' => 'Gibraltar',
                'alias' => Str::slug('Gibraltar'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 85,
                'code' => 'GR',
                'name' => 'Greece',
                'alias' => Str::slug('Greece'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 86,
                'code' => 'GL',
                'name' => 'Greenland',
                'alias' => Str::slug('Greenland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 87,
                'code' => 'GD',
                'name' => 'Grenada',
                'alias' => Str::slug('Grenada'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 88,
                'code' => 'GP',
                'name' => 'Guadeloupe',
                'alias' => Str::slug('Guadeloupe'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 89,
                'code' => 'GU',
                'name' => 'Guam',
                'alias' => Str::slug('Guam'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 90,
                'code' => 'GT',
                'name' => 'Guatemala',
                'alias' => Str::slug('Guatemala'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 91,
                'code' => 'GN',
                'name' => 'Guinea',
                'alias' => Str::slug('Guinea'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 92,
                'code' => 'GW',
                'name' => 'Guinea-Bissau',
                'alias' => Str::slug('Guinea-Bissau'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 93,
                'code' => 'GY',
                'name' => 'Guyana',
                'alias' => Str::slug('Guyana'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 94,
                'code' => 'HT',
                'name' => 'Haiti',
                'alias' => Str::slug('Haiti'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 95,
                'code' => 'HM',
                'name' => 'Heard and Mc Donald Islands',
                'alias' => Str::slug('Heard and Mc Donald Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 96,
                'code' => 'HN',
                'name' => 'Honduras',
                'alias' => Str::slug('Honduras'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 97,
                'code' => 'HK',
                'name' => 'Hong Kong',
                'alias' => Str::slug('Hong Kong'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 98,
                'code' => 'HU',
                'name' => 'Hungary',
                'alias' => Str::slug('Hungary'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 99,
                'code' => 'IS',
                'name' => 'Iceland',
                'alias' => Str::slug('Iceland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 100,
                'code' => 'IN',
                'name' => 'India',
                'alias' => Str::slug('India'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 101,
                'code' => 'ID',
                'name' => 'Indonesia',
                'alias' => Str::slug('Indonesia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 102,
                'code' => 'IR',
                'name' => 'Iran (Islamic Republic of)',
                'alias' => Str::slug('Iran (Islamic Republic of)'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 103,
                'code' => 'IQ',
                'name' => 'Iraq',
                'alias' => Str::slug('Iraq'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 104,
                'code' => 'IE',
                'name' => 'Ireland',
                'alias' => Str::slug('Ireland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 105,
                'code' => 'IL',
                'name' => 'Israel',
                'alias' => Str::slug('Israel'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 106,
                'code' => 'IT',
                'name' => 'Italy',
                'alias' => Str::slug('Italy'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 107,
                'code' => 'CI',
                'name' => 'Ivory Coast',
                'alias' => Str::slug('Ivory Coast'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 108,
                'code' => 'JM',
                'name' => 'Jamaica',
                'alias' => Str::slug('Jamaica'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 109,
                'code' => 'JP',
                'name' => 'Japan',
                'alias' => Str::slug('Japan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 110,
                'code' => 'JO',
                'name' => 'Jordan',
                'alias' => Str::slug('Jordan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 111,
                'code' => 'KZ',
                'name' => 'Kazakhstan',
                'alias' => Str::slug('Kazakhstan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 112,
                'code' => 'KE',
                'name' => 'Kenya',
                'alias' => Str::slug('Kenya'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 113,
                'code' => 'KI',
                'name' => 'Kiribati',
                'alias' => Str::slug('Kiribati'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 114,
                'code' => 'KP',
                'name' => 'Korea, Democratic People\'s Republic of',
                'alias' => Str::slug('Korea, Democratic People\'s Republic of'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 115,
                'code' => 'KR',
                'name' => 'Korea, Republic of',
                'alias' => Str::slug('Korea, Republic of'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 116,
                'code' => 'KW',
                'name' => 'Kuwait',
                'alias' => Str::slug('Kuwait'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 117,
                'code' => 'KG',
                'name' => 'Kyrgyzstan',
                'alias' => Str::slug('Kyrgyzstan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 118,
                'code' => 'LA',
                'name' => 'Lao People\'s Democratic Republic',
                'alias' => Str::slug('Lao People\'s Democratic Republic'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 119,
                'code' => 'LV',
                'name' => 'Latvia',
                'alias' => Str::slug('Latvia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 120,
                'code' => 'LB',
                'name' => 'Lebanon',
                'alias' => Str::slug('Lebanon'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 121,
                'code' => 'LS',
                'name' => 'Lesotho',
                'alias' => Str::slug('Lesotho'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 122,
                'code' => 'LR',
                'name' => 'Liberia',
                'alias' => Str::slug('Liberia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 123,
                'code' => 'LY',
                'name' => 'Libyan Arab Jamahiriya',
                'alias' => Str::slug('Libyan Arab Jamahiriya'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 124,
                'code' => 'LI',
                'name' => 'Liechtenstein',
                'alias' => Str::slug('Liechtenstein'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 125,
                'code' => 'LT',
                'name' => 'Lithuania',
                'alias' => Str::slug('Lithuania'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 126,
                'code' => 'LU',
                'name' => 'Luxembourg',
                'alias' => Str::slug('Luxembourg'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 127,
                'code' => 'MO',
                'name' => 'Macau',
                'alias' => Str::slug('Macau'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 128,
                'code' => 'MK',
                'name' => 'Macedonia',
                'alias' => Str::slug('Macedonia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 129,
                'code' => 'MG',
                'name' => 'Madagascar',
                'alias' => Str::slug('Madagascar'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 130,
                'code' => 'MW',
                'name' => 'Malawi',
                'alias' => Str::slug('Malawi'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 131,
                'code' => 'MY',
                'name' => 'Malaysia',
                'alias' => Str::slug('Malaysia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 132,
                'code' => 'MV',
                'name' => 'Maldives',
                'alias' => Str::slug('Maldives'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 133,
                'code' => 'ML',
                'name' => 'Mali',
                'alias' => Str::slug('Mali'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 134,
                'code' => 'MT',
                'name' => 'Malta',
                'alias' => Str::slug('Malta'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 135,
                'code' => 'MH',
                'name' => 'Marshall Islands',
                'alias' => Str::slug('Marshall Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 136,
                'code' => 'MQ',
                'name' => 'Martinique',
                'alias' => Str::slug('Martinique'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 137,
                'code' => 'MR',
                'name' => 'Mauritania',
                'alias' => Str::slug('Mauritania'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 138,
                'code' => 'MU',
                'name' => 'Mauritius',
                'alias' => Str::slug('Mauritius'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 139,
                'code' => 'TY',
                'name' => 'Mayotte',
                'alias' => Str::slug('Mayotte'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 140,
                'code' => 'MX',
                'name' => 'Mexico',
                'alias' => Str::slug('Mexico'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 141,
                'code' => 'FM',
                'name' => 'Micronesia, Federated States of',
                'alias' => Str::slug('Micronesia, Federated States of'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 142,
                'code' => 'MD',
                'name' => 'Moldova, Republic of',
                'alias' => Str::slug('Moldova, Republic of'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 143,
                'code' => 'MC',
                'name' => 'Monaco',
                'alias' => Str::slug('Monaco'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 144,
                'code' => 'MN',
                'name' => 'Mongolia',
                'alias' => Str::slug('Mongolia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 145,
                'code' => 'MS',
                'name' => 'Montserrat',
                'alias' => Str::slug('Montserrat'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 146,
                'code' => 'MA',
                'name' => 'Morocco',
                'alias' => Str::slug('Morocco'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 147,
                'code' => 'MZ',
                'name' => 'Mozambique',
                'alias' => Str::slug('Mozambique'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 148,
                'code' => 'MM',
                'name' => 'Myanmar',
                'alias' => Str::slug('Myanmar'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 149,
                'code' => 'NA',
                'name' => 'Namibia',
                'alias' => Str::slug('Namibia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 150,
                'code' => 'NR',
                'name' => 'Nauru',
                'alias' => Str::slug('Nauru'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 151,
                'code' => 'NP',
                'name' => 'Nepal',
                'alias' => Str::slug('Nepal'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 152,
                'code' => 'NL',
                'name' => 'Netherlands',
                'alias' => Str::slug('Netherlands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 153,
                'code' => 'AN',
                'name' => 'Netherlands Antilles',
                'alias' => Str::slug('Netherlands Antilles'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 154,
                'code' => 'NC',
                'name' => 'New Caledonia',
                'alias' => Str::slug('New Caledonia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 155,
                'code' => 'NZ',
                'name' => 'New Zealand',
                'alias' => Str::slug('New Zealand'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 156,
                'code' => 'NI',
                'name' => 'Nicaragua',
                'alias' => Str::slug('Nicaragua'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 157,
                'code' => 'NE',
                'name' => 'Niger',
                'alias' => Str::slug('Niger'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 158,
                'code' => 'NG',
                'name' => 'Nigeria',
                'alias' => Str::slug('Nigeria'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 159,
                'code' => 'NU',
                'name' => 'Niue',
                'alias' => Str::slug('Niue'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 160,
                'code' => 'NF',
                'name' => 'Norfork Island',
                'alias' => Str::slug('Norfork Island'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 161,
                'code' => 'MP',
                'name' => 'Northern Mariana Islands',
                'alias' => Str::slug('Northern Mariana Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 162,
                'code' => 'NO',
                'name' => 'Norway',
                'alias' => Str::slug('Norway'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 163,
                'code' => 'OM',
                'name' => 'Oman',
                'alias' => Str::slug('Oman'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 164,
                'code' => 'PK',
                'name' => 'Pakistan',
                'alias' => Str::slug('Pakistan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 165,
                'code' => 'PW',
                'name' => 'Palau',
                'alias' => Str::slug('Palau'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 166,
                'code' => 'PA',
                'name' => 'Panama',
                'alias' => Str::slug('Panama'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 167,
                'code' => 'PG',
                'name' => 'Papua New Guinea',
                'alias' => Str::slug('Papua New Guinea'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 168,
                'code' => 'PY',
                'name' => 'Paraguay',
                'alias' => Str::slug('Paraguay'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 169,
                'code' => 'PE',
                'name' => 'Peru',
                'alias' => Str::slug('Peru'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 170,
                'code' => 'PH',
                'name' => 'Philippines',
                'alias' => Str::slug('Philippines'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 171,
                'code' => 'PN',
                'name' => 'Pitcairn',
                'alias' => Str::slug('Pitcairn'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 172,
                'code' => 'PL',
                'name' => 'Poland',
                'alias' => Str::slug('Poland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 173,
                'code' => 'PT',
                'name' => 'Portugal',
                'alias' => Str::slug('Portugal'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 174,
                'code' => 'PR',
                'name' => 'Puerto Rico',
                'alias' => Str::slug('Puerto Rico'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 175,
                'code' => 'QA',
                'name' => 'Qatar',
                'alias' => Str::slug('Qatar'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 176,
                'code' => 'SS',
                'name' => 'Republic of South Sudan',
                'alias' => Str::slug('Republic of South Sudan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 177,
                'code' => 'RE',
                'name' => 'Reunion',
                'alias' => Str::slug('Reunion'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 178,
                'code' => 'RO',
                'name' => 'Romania',
                'alias' => Str::slug('Romania'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 179,
                'code' => 'RU',
                'name' => 'Russian Federation',
                'alias' => Str::slug('Russian Federation'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 180,
                'code' => 'RW',
                'name' => 'Rwanda',
                'alias' => Str::slug('Rwanda'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 181,
                'code' => 'KN',
                'name' => 'Saint Kitts and Nevis',
                'alias' => Str::slug('Saint Kitts and Nevis'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 182,
                'code' => 'LC',
                'name' => 'Saint Lucia',
                'alias' => Str::slug('Saint Lucia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 183,
                'code' => 'VC',
                'name' => 'Saint Vincent and the Grenadines',
                'alias' => Str::slug('Saint Vincent and the Grenadines'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 184,
                'code' => 'WS',
                'name' => 'Samoa',
                'alias' => Str::slug('Samoa'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 185,
                'code' => 'SM',
                'name' => 'San Marino',
                'alias' => Str::slug('San Marino'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 186,
                'code' => 'ST',
                'name' => 'Sao Tome and Principe',
                'alias' => Str::slug('Sao Tome and Principe'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 187,
                'code' => 'SA',
                'name' => 'Saudi Arabia',
                'alias' => Str::slug('Saudi Arabia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 188,
                'code' => 'SN',
                'name' => 'Senegal',
                'alias' => Str::slug('Senegal'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 189,
                'code' => 'RS',
                'name' => 'Serbia',
                'alias' => Str::slug('Serbia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 190,
                'code' => 'SC',
                'name' => 'Seychelles',
                'alias' => Str::slug('Seychelles'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 191,
                'code' => 'SL',
                'name' => 'Sierra Leone',
                'alias' => Str::slug('Sierra Leone'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 192,
                'code' => 'SG',
                'name' => 'Singapore',
                'alias' => Str::slug('Singapore'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 193,
                'code' => 'SK',
                'name' => 'Slovakia',
                'alias' => Str::slug('Slovakia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 194,
                'code' => 'SI',
                'name' => 'Slovenia',
                'alias' => Str::slug('Slovenia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 195,
                'code' => 'SB',
                'name' => 'Solomon Islands',
                'alias' => Str::slug('Solomon Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 196,
                'code' => 'SO',
                'name' => 'Somalia',
                'alias' => Str::slug('Somalia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 197,
                'code' => 'ZA',
                'name' => 'South Africa',
                'alias' => Str::slug('South Africa'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 198,
                'code' => 'GS',
                'name' => 'South Georgia South Sandwich Islands',
                'alias' => Str::slug('South Georgia South Sandwich Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 199,
                'code' => 'ES',
                'name' => 'Spain',
                'alias' => Str::slug('Spain'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 200,
                'code' => 'LK',
                'name' => 'Sri Lanka',
                'alias' => Str::slug('Sri Lanka'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 201,
                'code' => 'SH',
                'name' => 'St. Helena',
                'alias' => Str::slug('St. Helena'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 202,
                'code' => 'PM',
                'name' => 'St. Pierre and Miquelon',
                'alias' => Str::slug('St. Pierre and Miquelon'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 203,
                'code' => 'SD',
                'name' => 'Sudan',
                'alias' => Str::slug('Sudan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 204,
                'code' => 'SR',
                'name' => 'Suriname',
                'alias' => Str::slug('Suriname'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 205,
                'code' => 'SJ',
                'name' => 'Svalbarn and Jan Mayen Islands',
                'alias' => Str::slug('Svalbarn and Jan Mayen Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 206,
                'code' => 'SZ',
                'name' => 'Swaziland',
                'alias' => Str::slug('Swaziland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 207,
                'code' => 'SE',
                'name' => 'Sweden',
                'alias' => Str::slug('Sweden'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 208,
                'code' => 'CH',
                'name' => 'Switzerland',
                'alias' => Str::slug('Switzerland'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 209,
                'code' => 'SY',
                'name' => 'Syrian Arab Republic',
                'alias' => Str::slug('Syrian Arab Republic'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 210,
                'code' => 'TW',
                'name' => 'Taiwan',
                'alias' => Str::slug('Taiwan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 211,
                'code' => 'TJ',
                'name' => 'Tajikistan',
                'alias' => Str::slug('Tajikistan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 212,
                'code' => 'TZ',
                'name' => 'Tanzania, United Republic of',
                'alias' => Str::slug('Tanzania, United Republic of'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 213,
                'code' => 'TH',
                'name' => 'Thailand',
                'alias' => Str::slug('Thailand'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 214,
                'code' => 'TG',
                'name' => 'Togo',
                'alias' => Str::slug('Togo'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 215,
                'code' => 'TK',
                'name' => 'Tokelau',
                'alias' => Str::slug('Tokelau'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 216,
                'code' => 'TO',
                'name' => 'Tonga',
                'alias' => Str::slug('Tonga'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 217,
                'code' => 'TT',
                'name' => 'Trinidad and Tobago',
                'alias' => Str::slug('Trinidad and Tobago'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 218,
                'code' => 'TN',
                'name' => 'Tunisia',
                'alias' => Str::slug('Tunisia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 219,
                'code' => 'TR',
                'name' => 'Turkey',
                'alias' => Str::slug('Turkey'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 220,
                'code' => 'TM',
                'name' => 'Turkmenistan',
                'alias' => Str::slug('Turkmenistan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 221,
                'code' => 'TC',
                'name' => 'Turks and Caicos Islands',
                'alias' => Str::slug('Turks and Caicos Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 222,
                'code' => 'TV',
                'name' => 'Tuvalu',
                'alias' => Str::slug('Tuvalu'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 223,
                'code' => 'UG',
                'name' => 'Uganda',
                'alias' => Str::slug('Uganda'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 224,
                'code' => 'UA',
                'name' => 'Ukraine',
                'alias' => Str::slug('Ukraine'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 225,
                'code' => 'AE',
                'name' => 'United Arab Emirates',
                'alias' => Str::slug('United Arab Emirates'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 226,
                'code' => 'GB',
                'name' => 'United Kingdom',
                'alias' => Str::slug('United Kingdom'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 227,
                'code' => 'UM',
                'name' => 'United States minor outlying islands',
                'alias' => Str::slug('United States minor outlying islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 228,
                'code' => 'UY',
                'name' => 'Uruguay',
                'alias' => Str::slug('Uruguay'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 229,
                'code' => 'UZ',
                'name' => 'Uzbekistan',
                'alias' => Str::slug('Uzbekistan'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 230,
                'code' => 'VU',
                'name' => 'Vanuatu',
                'alias' => Str::slug('Vanuatu'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 231,
                'code' => 'VA',
                'name' => 'Vatican City State',
                'alias' => Str::slug('Vatican City State'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 232,
                'code' => 'VE',
                'name' => 'Venezuela',
                'alias' => Str::slug('Venezuela'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 233,
                'code' => 'VN',
                'name' => 'Vietnam',
                'alias' => Str::slug('Vietnam'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 234,
                'code' => 'VG',
                'name' => 'Virgin Islands (British)',
                'alias' => Str::slug('Virgin Islands (British)'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 235,
                'code' => 'VI',
                'name' => 'Virgin Islands (U.S.)',
                'alias' => Str::slug('Virgin Islands (U.S.)'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 236,
                'code' => 'WF',
                'name' => 'Wallis and Futuna Islands',
                'alias' => Str::slug('Wallis and Futuna Islands'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 237,
                'code' => 'EH',
                'name' => 'Western Sahara',
                'alias' => Str::slug('Western Sahara'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 238,
                'code' => 'YE',
                'name' => 'Yemen',
                'alias' => Str::slug('Yemen'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 239,
                'code' => 'YU',
                'name' => 'Yugoslavia',
                'alias' => Str::slug('Yugoslavia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 240,
                'code' => 'ZR',
                'name' => 'Zaire',
                'alias' => Str::slug('Zaire'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 241,
                'code' => 'ZM',
                'name' => 'Zambia',
                'alias' => Str::slug('Zambia'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
			array(
                'id' => 242,
                'code' => 'ZW',
                'name' => 'Zimbabwe',
                'alias' => Str::slug('Zimbabwe'),
                'created_at' => date('Y-m-d H:i:s'),
            ),
        );

        $items = array_chunk($countries, 10);

        foreach ($items as $key => $country) {
            \DB::table('countries')->insert($country);
        }
    }
}
